<h1>Статьи</h1>
<a href="/admin/article/add/">Добавить</a>

<?php
$flash = $this->flashMessenger();
$flash->setMessageOpenFormat('<div%s>
     <button type="button" class="close" data-dismiss="alert" aria-hidden="true">
         &times;
     </button>
     <ul><li>')
    ->setMessageSeparatorString('</li><li>')
    ->setMessageCloseString('</li></ul></div>');

echo $flash->render('error',   array('alert', 'alert-dismissible', 'alert-danger'));
echo $flash->render('info',    array('alert', 'alert-dismissible', 'alert-info'));
echo $flash->render('default', array('alert', 'alert-dismissible', 'alert-warning'));
echo $flash->render('success', array('alert', 'alert-dismissible', 'alert-success'));
?>

<table class="table table-striped table-bordered">
    <tbody>
    <tr>
        <th>№</th>
        <th>Категория</th>
        <th>Заголовок</th>
        <th>Статья</th>
        <th>Начало</th>
        <th>Опубликованно</th>
        <th>Действие</th>
    </tr>
    <?php foreach ($articles as $item):?>
    <?php
        $category = $item->getCategory();
        if($category){
            $catName = $category->getCategoryName();
        } else {
            $catName = '';
        }

        if($item->getIsPublic()){
            $isPublic = 'Да';
        } else {
            $isPublic = 'Нет';
        }
    ?>

        <tr>
            <td><?=$item->getId()?></td>
            <td><?=$catName?></td>
            <td><?=$item->getTitle()?></td>
            <td><?=$item->getArticleForTable()?></td>
            <td><?=$item->getShortArticleForTable()?></td>
            <td><?=$isPublic?></td>
            <td>
                <a href="<?=$this->url('admin/article', array('action'=>'edit', 'id'=>$item->getId()))?>">Edit</a>
                &nbsp;
                <a href="<?=$this->url('admin/article', array('action'=>'delete', 'id'=>$item->getId()))?>"
                   onclick="if (confirm('Удалить запись?')){document.location = this.href;} return false">Delete</a>
            </td>
        </tr>
    <?php endforeach;?>
    </tbody>
</table>

<?php echo $this->paginationControl($articles,'Sliding', 'pagination_control', ['route' => 'admin/article']);