<h1>Категории</h1>
<a href="/admin/category/add/">Добавить</a>

<?php
$flash = $this->flashMessenger();
$flash->setMessageOpenFormat('<div%s>
     <button type="button" class="close" data-dismiss="alert" aria-hidden="true">
         &times;
     </button>
     <ul><li>')
    ->setMessageSeparatorString('</li><li>')
    ->setMessageCloseString('</li></ul></div>');

echo $flash->render('error',   array('alert', 'alert-dismissible', 'alert-danger'));
echo $flash->render('info',    array('alert', 'alert-dismissible', 'alert-info'));
echo $flash->render('default', array('alert', 'alert-dismissible', 'alert-warning'));
echo $flash->render('success', array('alert', 'alert-dismissible', 'alert-success'));
?>

<table class="table table-striped table-bordered">
    <tbody>
    <tr>
        <th>№</th>
        <th>Ключ</th>
        <th>Название</th>
        <th>Действие</th>
    </tr>
        <?php foreach ($category as $item):?>
    <tr>
            <td><?=$item->getId()?></td>
            <td><?=$item->getCategoryKey()?></td>
            <td><?=$item->getCategoryName()?></td>
            <td>
                <a href="<?=$this->url('admin/category', array('action'=>'edit', 'id'=>$item->getId()))?>">Edit</a>
                &nbsp;
                <a href="<?=$this->url('admin/category', array('action'=>'delete', 'id'=>$item->getId()))?>"
                   onclick="if (confirm('Удалить запись?')){document.location = this.href;} return false">Delete</a>
            </td>
    </tr>
        <?php endforeach;?>
    </tbody>
</table>