<h1>Коментарии</h1>

<?php
$flash = $this->flashMessenger();
$flash->setMessageOpenFormat('<div%s>
     <button type="button" class="close" data-dismiss="alert" aria-hidden="true">
         &times;
     </button>
     <ul><li>')
    ->setMessageSeparatorString('</li><li>')
    ->setMessageCloseString('</li></ul></div>');

echo $flash->render('error',   array('alert', 'alert-dismissible', 'alert-danger'));
echo $flash->render('info',    array('alert', 'alert-dismissible', 'alert-info'));
echo $flash->render('default', array('alert', 'alert-dismissible', 'alert-warning'));
echo $flash->render('success', array('alert', 'alert-dismissible', 'alert-success'));
?>

<table class="table table-striped table-bordered">
    <tbody>
    <tr>
        <th>№</th>
        <th>Статья</th>
        <th>Email</th>
        <th>Коментарий</th>
        <th></th>
    </tr>
        <?php foreach ($comment as $item):?>
    <tr>
        <td><?=$item->getId()?></td>
        <td><?=$item->getArticle()->getTitle()?></td>
        <td><?=$item->getUserEmail()?></td>
        <td><?=$item->getComment()?></td>
        <td>
            <a href="<?=$this->url('admin/comment', array('action'=>'delete', 'id'=>$item->getId()))?>"
               onclick="if (confirm('Удалить коментарий?')){document.location = this.href;} return false">Delete</a>
         </td>
    </tr>
        <?php endforeach;?>
    </tbody>
</table>

<?php echo $this->paginationControl($comment,'Sliding', 'pagination_control', ['route' => 'admin/comment']);